name: Java Ant CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17

    - name: Install Ant
      run: sudo apt-get update && sudo apt-get install -y ant

    - name: Fix Java version
      run: sed -i 's/1.6/1.8/g' nbproject/project.properties

    - name: Build
      run: ant clean jar

    - name: Test
      run: ant test
